version: '3'

services:
  rust:
    build:
      context: ./infura
      dockerfile: Dockerfile
    container_name: rust
    working_dir: /opt/src
    tty: true
    volumes: 
      - ./src:/opt/src
    ports:
      - "8080:8080"
    env_file:
      - env/.env
    # depends_on:
    #   - mysql

  # mysql:
  #   build: ./mysql
  #   container_name: mysql
  #   platform: linux/x86_64
  #   command:
  #     - --default-authentication-plugin=mysql_native_password
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_0900_ai_ci
  #   ports:
  #     - 33063:3306
  #   volumes:
  #     - ./mysql/db-store:/var/lib/mysql
  #     - ./mysql/query:/opt/query
  #   env_file:
  #     - env/.env.mysql